[package]
name = "project1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.0"
rocket = "0.4.9"
rocket_contrib = { version = "0.4.9", features = ["json"] }
